#组件信息
app: Epidemic
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: main # (必填) 创建的实例名称，请修改成您的实例名称

inputs:
  name: ${app} # 函数名称
  src: ./  # 代码路径
  handler: main.main # 入口
  runtime: Python3.6 # 云函数运行时的环境
  region: ap-guangzhou # 云函数所在区域
  description: '易班疫情防控签到'
  timeout: 900 # 超时
  events: # 触发器
    - timer: # 定时触发器
        name: '每日签到' # 触发器名称
        parameters:
          cronExpression: '0 1 7,15 * * * *'
          # cronExpression: '0 1 11,15 * * * *'
          enable: true
