#组件信息
app: Epidemic
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: main # (必填) 创建的实例名称，请修改成您的实例名称
inputs:
  name: ${app} #函数名称
  src: ./  #代码路径
  handler: main.main #入口
  runtime: Python3.6 # 云函数运行时的环境
  region: ap-guangzhou # 云函数所在区域
  description: '易班疫情防控签到'
  memorySize: 512 # 内存大小，单位MB
  timeout: 180 # 函数执行超时时间，单位秒
  retryNum: 1 # 重试次数
  events: # 触发器
    - timer: # 定时触发器
      name: ${name} #触发器名称
      parameters:
        cronExpression: '0 1 7,15 * * * *'
        enable: true
  environment: #  环境变量
    variables: #  环境变量对象
      TZ: Asia/Shanghai