name: Run Task

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,23 * * *'

jobs:
  post-data:
    env:
      USERS_COVER: ${{ secrets.USERS_COVER }}
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v2

    - name: Set up Python
      if: env.USERS_COVER
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Set time zone
      if: env.USERS_COVER
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Install dependencies
      if: env.USERS_COVER
      run: |
        pip install -r requirements.txt
        
    - name: Build and publish
      if: env.USERS_COVER
      run: |
        echo "$USERS_COVER" > ./config.json
        python main.py
